services:  
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "http://127.0.0.1:3000", "-qO", "/dev/null"]
      interval: 30s
      retries: 10
    network_mode: host
    # ports:
     #  - "53:53/tcp"
     #  - "53:53/udp"
     #  - "68:68/tcp"
      # - "68:68/udp"
      # - "80:80/tcp"
      # - "443:443/tcp"
      # - "443:443/udp"
     #  - "853:853/tcp"
    volumes:
      - ./adguardhome/work:/opt/adguardhome/work
      - ./adguardhome/conf:/opt/adguardhome/conf
      - ./adguardhome/certs:/opt/adguardhome/certs
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.adguardhome.loadbalancer.server.port=3000"
      - "traefik.http.routers.adguardhome.rule=(Host(`${ADGUARD_HOSTNAME}`))"
      - "traefik.http.routers.adguardhome.tls=true"
      - "traefik.http.routers.adguardhome.tls.certresolver=myresolver"
      - homepage.group=Utilities
      - homepage.name=Adguard
      - homepage.icon=adguard-home.png
      - homepage.href=https://${ADGUARD_HOSTNAME}
      - homepage.description=DNS Adblocker
      - homepage.weight=0
      - homepage.widget.type=adguard
      - homepage.widget.url=https://${ADGUARD_HOSTNAME}
      - homepage.widget.username=${ADGUARD_USERNAME}
      - homepage.widget.password=${ADGUARD_PASSWORD}
    profiles:
      - adguardhome

  traefik-certs-dumper:
    image: ghcr.io/ldez/traefik-certs-dumper:latest
    container_name: traefik-certs-dumper
    restart: always
    entrypoint: sh -c '
      apk add jq
      ; while ! [ -e /data/acme.json ]
      || ! [ `jq ".[] | .Certificates | length" /data/acme.json` != 0 ]; do
      sleep 1
      ; done
      && traefik-certs-dumper file --version v2 --watch
      --clean false
      --source /data/acme.json --dest /certs'
    volumes:
      - ./letsencrypt:/data
      - ./adguardhome/certs:/certs
    profiles:
      - adguardhome


